### ISSUE TITLE
"Invalid magic in texture" error

### ISSUE THREAD

**Issue by CirnoChan999** [torandi/HzDTextureExplorer#1]
Hello,

Thank you for your work on this program, now if only I can get it to work.

I am trying to import a face texture for Gaia, but I keep getting the "Invalid magic" error and I don't know what I did wrong.

This is the texture I'm trying to import (includes the .core and .stream files).
https://we.tl/t-IyFJX74XYi

I should also point out that while installing HzDTextureExplorer, it told me I needed .NET 5.0.0 but the link redirected me to a 5.0.15 installer, which caused the program to keep asking for .NET 5.0.0.

Regards

**Comment by mithkr** [comment]
see my pull request.
https://github.com/torandi/HzDTextureExplorer/pull/3
Attached the pre build binary with the latest changes. Build with .NET 8.0 SDK.
[HzdTextureExplorer-v0.50+mithkr-patch2.zip](https://github.com/torandi/HzDTextureExplorer/files/13801771/HzdTextureExplorer-v0.50%2Bmithkr-patch2.zip)

**Comment by torandi** [comment]
I have now published a release with this and the other changes from mithkr
